### ISSUE TITLE
Add details José

### ISSUE THREAD

**Issue by GeertvanGeest** [elixir-europe-training/ELIXIR-Training-SPLASH#195]
Richer details: 

```yml
Jose Alejandro Romero Herrera:
    git: joseale2310
    node: DK
    affiliation: Copenhangen University
    orcid: 0000-0002-4765-2087
    role: 
```
